package.path="?/init.lua;?.lua;"..package.path
local multi = require("multi")
test = multi:newHyperThreadedProcess("test")
test:newLoop(function()
	print("HI!")
end)
test:newLoop(function()
	print("HI2!")
	thread.sleep(.5)
end)
multi:newAlarm(3):OnRing(function()
	test:Sleep(10)
end)
test:Start()
multi:mainloop()

