package.path="?.lua;?/init.lua;?.lua;"..package.path
local multi, thread = require("multi"):init()
GLOBAL,THREAD = require("multi.integration.lanesManager"):init()
serv = multi:newService(function(self,dat)
	print("Service Uptime: ",self:GetUpTime())
end)
serv.OnError(function(...)
	print(...)
end)
serv.OnStarted(function(self,data)
	print("Started!",self.Type)
end)
serv:Start()
serv:SetPriority(multi.Priority_Idle)
multi:mainloop()