name: Build & Run tests Love2d

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
    - name: Install love2d
      run: |
        sudo apt install fuse
        wget https://github.com/love2d/love/releases/download/11.4/love-11.4-x86_64.AppImage -O love.AppImage
        sudo chmod +x love.AppImage
    - name: Run Tests
      run: |
        ./love.AppImage tests