name: Build & Run tests (Ubuntu/Love2d)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: "ubuntu-latest"
    steps:
    - uses: actions/checkout@v2
    - uses: nhartland/love-build@v1-beta4
      with:
        app_name: 'love_test'
        love_version: '11.4'
        source_dir: 'test'
    - name: Run Tests
      run: |
        ./release/love_tests