name: build & run tests (NIX)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build-type: [Release] # Debug
        lua: ["lua 5.1", "lua 5.2", "lua 5.3", "lua 5.4", "luajit 2.1.0-beta3"]
        os: ["ubuntu-latest"]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - uses: actions/setup-python@v2
      with:
        python-version: '3.8'
    - name: Setup env
      run: |
        pip install hererocks
        hererocks lua-pkg --${{ matrix.lua }} -rlatest

    - name: Install lanes
      run: |
        source ${{github.workspace}}/lua-pkg/bin/activate
        luarocks install lanes

    - name: Run Tests
      run: |
        source ${{github.workspace}}/lua-pkg/bin/activate
        lua tests/runtests.lua
